world:addCollisionClass("Breakable")
world:addCollisionClass("Crate")
world:addCollisionClass("Wall")
world:addCollisionClass("Ground")
world:addCollisionClass("Gate")
world:addCollisionClass("Chest")
world:addCollisionClass("HealthBottle", {ignores = {"All", except = {"Ground"}}})
world:addCollisionClass("LoadingZone", {ignores = {"All"}})
world:addCollisionClass("InteriorZone", {ignores = {"All"}})
world:addCollisionClass("Enemy", {ignores = {"Enemy"}, enter = {"Wall", "Ground", "Crate", "LoadingZone"}})
world:addCollisionClass("Pickup", {ignores = {"All", except = {"Ground"}}})
world:addCollisionClass("Player", {ignores = {"Enemy"}, enter = {"Enemy", "LoadingZone", "Pickup", "HealthBottle"}})
world:addCollisionClass("RespawnPoint", {ignores = {"All"}, enter = {"Player"}})
world:addCollisionClass("KillZone", {ignores = {"All"}, enter = {"Player", "Enemy", "Crate"}})
world:addCollisionClass("Trigger", {ignores = {"All"}, enter = {"Player"}})
world:addCollisionClass("MovingPlatform") -- mostly here for querying purposes only
world:addCollisionClass("EnemyProjectile", {ignores = {"Enemy", "EnemyProjectile", "Crate", "Player"}, enter = {"Player", "Enemy", "Wall", "Ground", "Crate"}})
world:addCollisionClass("BasicSpell", {ignores = {"Player", "BasicSpell", "Enemy", "EnemyProjectile"}, enter = {"Breakable", "Crate", "Enemy", "Ground", 'Wall', "Gate"}})
world:addCollisionClass("Bomb", {ignores = {"Bomb", "Player", "BasicSpell", "Enemy", "EnemyProjectile"}})
world:addCollisionClass("Ghost", {ignores = {"All"}})
-- COLLISION EVENTS WILL STILL TRIGGER IF THEY IGNORE CLASSES (Only prevents physical contact, not collision events)
-- ^ unless world:setExplicitCollisionEvents(true) is called, which it is.