return {
    hitbox = require"src.ECS.ComponentTypes.Primitives.Hitbox",
    position = require"src.ECS.ComponentTypes.Primitives.Position",
    body = require"src.ECS.ComponentTypes.Primitives.Body",
    liftable = require"src.ECS.ComponentTypes.Primitives.Liftable",
    interactQueryData = require"src.ECS.ComponentTypes.Data.InteractQueryData",
    inputData = require"src.ECS.ComponentTypes.Data.InputData",
    movementData = require"src.ECS.ComponentTypes.Data.MovementData",
    knockbackData = require"src.ECS.ComponentTypes.Data.KnockbackData",
    jumpData = require"src.ECS.ComponentTypes.Data.JumpData",
    healthData = require"src.ECS.ComponentTypes.Data.HealthData",
    saveData = require"src.ECS.ComponentTypes.Data.SaveData",
    weaponData = require"src.ECS.ComponentTypes.Data.WeaponData",
    inventory = require"src.ECS.ComponentTypes.Primitives.Inventory",
    camera = require"src.ECS.ComponentTypes.Primitives.Camera",
    collisionData = require"src.ECS.ComponentTypes.Data.CollisionData",
    scriptData = require"src.ECS.ComponentTypes.Data.ScriptData",
    interactableData = require"src.ECS.ComponentTypes.Data.InteractableData",
    zoneData = require"src.ECS.ComponentTypes.Data.ZoneData",
    passageData = require"src.ECS.ComponentTypes.Data.PassageData",
    tiledID = require"src.ECS.ComponentTypes.Primitives.TiledID",
    creationData = require"src.ECS.ComponentTypes.Data.CreationData",
    signalData = require"src.ECS.ComponentTypes.Data.SignalData",
    breakable = require"src.ECS.ComponentTypes.Primitives.Breakable",
    respawnData = require"src.ECS.ComponentTypes.Data.RespawnData",
    platformData = require"src.ECS.ComponentTypes.Physics.PlatformData"
}